name: report tech news
on:
  push:
    branches:
      - bichakala-bobeh

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/report_news

    name: Build And Send
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send the news api message to osscameroon channel
        run: make run
