name: report tech news
on:
  push:
    branches:
      - bichakala-bobeh

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/report_news

    name: Build And Send
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send the news api message to osscameroon channel
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: make -s run > news_feed_message

      - name: Dump message
        run: cat news_feed_message

      - name: send contribution report to osscameroon channel
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_file: ./.github/workflows/report_news/news_feed_message
